### ISSUE TITLE
Ruby 2.2.3 (x64) Windows broken

### ISSUE THREAD

**Issue by idstein** [devunwired/apktools#15]
When using the 64bit build of Windows the recent changes has resulted in a Nil:Class does not support unpack exception. 

Looks like an overflow on the data adress. 

Same APK works using 0.7.0 with Ruby 1.9.3.

**Comment by devunwired** [comment]
This is the same error I was receiving when parsing AppCompat APKs reported on Issue #12. I had closed the issue because it inexplicably disappeared. Now I know why…I had switched over to 1.9.3 to test something else. As you've noted, the issue remains in 2.2.3, so I'll re-open that issue and close this one.
