### ISSUE TITLE
Get certificate and verify apk signature

### ISSUE THREAD

**Issue by mdjamal** [devunwired/apktools#9]
Hi,

Is there a method to check if the APK is signed. 

Thanks.

**Comment by idstein** [comment]
You can use the jarsigner from the JDK. It accepts a command line argument "-verify". 

A signed APK nothing else than an unsigned APK (=zip archive with packaged resources + packaged compiled DEX code), signed using the jarsigner and finally aligned to 4-bytes using Androids zip align.

**Comment by devunwired** [comment]
If you just want to check if an APK is signed or not, examine the contents and look for the presence of the `META-INF/`directory. It will only exist on a signed APK. Since APKs are just zip archives, you can use your favorite zip library (this project uses `rubyzip`) to inspect the contents.

If you need to verify that the signature was applied correctly, you can use the method @idstein mentioned.

This tool specifically inspects and decodes resource values, however. Closing this as out of scope for this particular project.

**Comment by mdjamal** [comment]
Thank you @idstein and @devunwired looks like jarsigner is the way forward, guess I would have to use shell command.
